engines:
  fixme:
    enabled: false

  rubocop:
    enabled: true
    channel: rubocop-0-52

  brakeman:
    enabled: true

  bundler-audit:
    enabled: true

  eslint:
    enabled: true

exclude_paths:
  - spec/**/*
  - vendor/**/*
  - public/**/*
